name: snapology # you probably want to 'snapcraft register <name>'
version: "v2.0.0"
summary: this is a test golang app
description: |
  Golang hello world app for testing snaps

grade: stable
confinement: strict
base: core18

parts:
  snapology:
    plugin: go
    go-importpath: github.com/glower/snapology
    source: .
    source-type: git

apps:
  snapology:
    command: bin/snapology