name: hello-snap # you probably want to 'snapcraft register <name>'
version: "v1.1.0"
summary: this is a test golang app
description: |
  Golang hello world app for testing snaps

grade: stable
confinement: strict
base: core18

parts:
  hello-snap:
    plugin: go
    go-importpath: github.com/glower/hello-snap
    source: .
    source-type: git

apps:
  hello-snap:
    command: bin/hello-snap