name: hello-berlinski # you probably want to 'snapcraft register <name>'
version: "v2.0.0"
summary: this is a test golang app
description: |
  Golang hello world app for testing snaps

grade: stable
confinement: strict
base: core18

parts:
  hello-berlinski:
    plugin: go
    go-importpath: github.com/glower/hello-berlinski
    source: .
    source-type: git

apps:
  hello-berlinski:
    command: bin/hello-berlinski