name: snap-test-1
version: "2.0.0"
summary: this is a test golang app
description: |
  Golang hello world app for testing snaps

grade: stable
confinement: strict

parts:
  go:
    source-tag: go1.13
    source-depth: 1
  hello-berlinski:
    plugin: go
    go-importpath: github.com/glower/hello-berlinski
    source: .
    source-type: git
    after: [go]

apps:
  hello-berlinski:
    command: bin/hello-berlinski
